import Head from "next/head";
import { useState } from "react";

export default function Home() {

// Declarar uma nova variavel que pega os dados digitados
const [data, setData] = useState ({
name:'',
email:'',
telefone:'',
content:''

});

// receber os dados do formulário
const valorInput = e => setData({...data, [e.target.name]: e.target.value})

// executar a funçao de mensagem quando o usuário clicar no botão
const sendMsg = (e) => {

e.preventDefault();

  console.log(`Nome: ${data.name}`)
  console.log(`E-mail: ${data.email}`)
  console.log(`Telefone: ${data.telefone}`)
  console.log(`Observação: ${data.content}`)
}

  return (
    <>
      <Head>
        <title>TI-23 Storage Control</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <h2>Formulário de contato</h2>

       <form onSubmit={sendMsg}>
        <label>Nome:</label>
        <input type="text" name="name" placeholder="Digite seu nome" onChange={valorInput} />
        <br></br>

        <label>Email:</label>
        <input type="email" name="email" placeholder="Digite seu e-mail" onChange={valorInput} />
        <br/>

        <label>Telefone:</label>
        <input type="text" name="telefone" placeholder="Digite seu telefone/celular" style={{width:"155px"}} onChange={valorInput} />
        <br/>

        <label>Observações:</label>
        <textarea name="content" cols={30} rows={10} onChange={valorInput}></textarea>

        <button type="submit">Enviar</button><br></br>
       </form>
      </main>
    </>
  );
}
